# Generated by Django 5.0.3 on 2024-03-28 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='emotion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='what_to_do_app.emotioncategory'),
        ),
        migrations.AddField(
            model_name='emotion',
            name='emotion_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='what_to_do_app.emotiontype'),
        ),
    ]
