# Generated by Django 5.0.3 on 2024-03-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_to_do_app', '0002_emotioncategory_emotiontype_alter_emotion_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotiontype',
            name='weight',
            field=models.IntegerField(choices=[(1, 'Positive'), (-1, 'Negative')], default=1),
            preserve_default=False,
        ),
    ]
