# Generated by Django 5.0.3 on 2024-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_to_do_app', '0003_emotiontype_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.AddField(
            model_name='activityevent',
            name='activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='activity_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
