# Generated by Django 5.0.3 on 2024-04-02 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_to_do_app', '0004_remove_activity_activity_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivityemotion',
            old_name='user_activity',
            new_name='activity',
        ),
        migrations.AddField(
            model_name='useractivityemotion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
