# Generated by Django 5.0.3 on 2024-04-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_to_do_app', '0006_remove_activity_user_emotions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='activity_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
